ALTER TABLE "DownloadJob" ADD COLUMN IF NOT EXISTS "formatLabel" TEXT;
ALTER TABLE "DownloadJob" ADD COLUMN IF NOT EXISTS "phase" TEXT NOT NULL DEFAULT 'queued';
ALTER TABLE "DownloadJob" ADD COLUMN IF NOT EXISTS "downloadProgress" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DownloadJob" ADD COLUMN IF NOT EXISTS "convertProgress" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DownloadJob" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
