# Env file ownership and local dev overrides (sourced by install.sh / deploy-native.sh).
# Requires: APP_DIR, SOURCE_DIR, SYSTEM_USER, and optionally APP_PORT, APP_URL, DEV_INSTALL.

# Who should own the git clone .env when install runs via sudo from a home directory.
source_tree_env_owner() {
  local sudo_user="${SUDO_USER:-}"
  if [[ "${SOURCE_DIR}" == /home/* && -n "${sudo_user}" && "${sudo_user}" != "root" ]]; then
    echo "${sudo_user}"
    return
  fi
  echo "${SYSTEM_USER}"
}

detect_install_mode() {
  DEV_INSTALL="${YAYTD_DEV_INSTALL:-0}"
  ENV_FILE_OWNER="${SYSTEM_USER}"
  RUN_AS_USER="${SYSTEM_USER}"

  if [[ "${DEV_INSTALL}" == "1" ]] || [[ "${APP_DIR}" == "${SOURCE_DIR}" && "${SOURCE_DIR}" == /home/* ]]; then
    DEV_INSTALL=1
    local sudo_user="${SUDO_USER:-}"
    if [[ -n "${sudo_user}" && "${sudo_user}" != "root" ]]; then
      ENV_FILE_OWNER="${sudo_user}"
      RUN_AS_USER="${sudo_user}"
      if [[ -z "${YAYTD_INSTALL_SYSTEMD:-}" ]]; then
        INSTALL_SYSTEMD=0
      fi
    fi
  fi
}

finalize_env_file_permissions() {
  local app_env="${APP_DIR}/.env"
  local src_env="${SOURCE_DIR}/.env"
  local src_owner
  src_owner="$(source_tree_env_owner)"

  if [[ -f "${app_env}" ]]; then
    chown "${SYSTEM_USER}:${SYSTEM_USER}" "${app_env}" 2>/dev/null || true
    chmod 600 "${app_env}"
  fi

  if [[ -f "${src_env}" && "${src_env}" != "${app_env}" ]]; then
    chown "${src_owner}:${src_owner}" "${src_env}" 2>/dev/null || true
    chmod 600 "${src_env}"
  elif [[ "${DEV_INSTALL:-0}" == "1" && -f "${src_env}" ]]; then
    chown "${ENV_FILE_OWNER}:${ENV_FILE_OWNER}" "${src_env}" 2>/dev/null || true
    chmod 600 "${src_env}"
  fi
}

write_dev_env_local_file() {
  [[ "${DEV_INSTALL:-0}" == "1" ]] || return 0

  local target="${APP_DIR}/.env.development.local"
  local dev_url="${APP_URL}"
  if [[ "${dev_url}" != http://localhost* && "${dev_url}" != https://localhost* ]]; then
    dev_url="http://localhost:${APP_PORT:-3000}"
  fi

  mkdir -p /tmp/yaytd-downloads
  chown "${ENV_FILE_OWNER}:${ENV_FILE_OWNER}" /tmp/yaytd-downloads 2>/dev/null || true

  cat > "${target}" <<EOF
# Local dev overrides (generated by scripts/install.sh — gitignored)
NODE_ENV=development
TEMP_DOWNLOAD_DIR=/tmp/yaytd-downloads
APP_URL="${dev_url}"
AUTH_URL="${dev_url}"
NEXTAUTH_URL="${dev_url}"
NEXT_PUBLIC_APP_URL="${dev_url}"
TRUST_PROXY=false
EOF
  chmod 600 "${target}"
  chown "${ENV_FILE_OWNER}:${ENV_FILE_OWNER}" "${target}" 2>/dev/null || true

  if [[ "${APP_DIR}" != "${SOURCE_DIR}" && -d "${SOURCE_DIR}" ]]; then
    cp "${target}" "${SOURCE_DIR}/.env.development.local"
    chown "${ENV_FILE_OWNER}:${ENV_FILE_OWNER}" "${SOURCE_DIR}/.env.development.local" 2>/dev/null || true
    chmod 600 "${SOURCE_DIR}/.env.development.local"
  fi
}
